export const UPDATE_POSTS = 'UPDATE_POSTS';
export const POST_LOADING = 'POST_LOADING';
export const CLEAR_POSTS = 'CLEAR_POSTS';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOG_OUT = 'LOG_OUT';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_START';

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';

export const START_FRIEND_ACTION = 'START_FRIEND_ACTION';
export const ADD_FRIEDNS_SUCCESS = 'ADD_FRIEDNS_SUCCESS';
export const ADD_FRIEDNS_FAILIOUR = 'ADD_FRIEDNS_FAILIOUR';

export const REMOVE_FRIEND = 'REMOVE_FRIEND';
export const REMOVE_SEARCH_RESULT = 'REMOVE_SEARCH_RESULT';
export const SEARCH_USER_START = 'SEARCH_USER_START';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_FAILIOUR = 'SEARCH_USER_FAILIOUR';
export const CLEAR_SEARCH_START = 'CLEAR_SEARCH_START';

export const CLEAR_FRIENDS_STATE = 'CLEAR_FRIENDS_STATE';
